### ISSUE TITLE
FileNotFoundError: No such file or directory: 'user/username.txt'

### ISSUE THREAD

**Issue by zenthm** [Fex-Development/python-os#1]
Hi there, probably I'm your first contributor.

So here's the problem when you run **testos.py** and insert 1 to do the setup and enter your name and password it gives this error, and it seems like you need to create a folder named **user** before running it

**Comment by nullure** [comment]
you have to creat a directory called user for it to work

**Comment by nullure** [comment]
i tried to upload the folder in this repo
but github desktop didnt support it
